// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqsZGs2inKoqHxo67MBd_zzKeNVmdteKQ',
    appId: '1:669619013720:web:823c2dae1b1fd4fb59622d',
    messagingSenderId: '669619013720',
    projectId: 'web-chat-app-9a3ce',
    authDomain: 'web-chat-app-9a3ce.firebaseapp.com',
    storageBucket: 'web-chat-app-9a3ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBFTUNbSMMYJvWqnquqPFiw1qwuE7UQZE',
    appId: '1:669619013720:android:feaec0d7c30829c559622d',
    messagingSenderId: '669619013720',
    projectId: 'web-chat-app-9a3ce',
    storageBucket: 'web-chat-app-9a3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3t5iyh3F39Qny8DP9NXkcbZ3ECaP_U8o',
    appId: '1:669619013720:ios:213b59c37838d90f59622d',
    messagingSenderId: '669619013720',
    projectId: 'web-chat-app-9a3ce',
    storageBucket: 'web-chat-app-9a3ce.appspot.com',
    iosBundleId: 'com.example.webChatApp',
  );
}
